"""
Validate the actual intended configs generated by Nautobot's intended job.

Unlike test_template_render.py (which renders from mock data), this test
validates the REAL output that Nautobot produced with live SoT data. These
are the exact files that will become Config Plans and get pushed to devices.

This runs against golden-config/intended-configs/**/*.cfg and catches:
- Invalid CLI syntax that Batfish's vendor grammar rejects
- Undefined references (route-maps, ACLs referenced but never defined)
- Configs that are suspiciously short (render failures that produced stubs)
- Python None leaking into generated output

Requirements:
  - Batfish container running for parse validation
  - Intended configs must exist (run Nautobot's intended job first)

Run with: pytest tests/test_intended_configs.py -v
"""

import os
import shutil
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
INTENDED_DIR = REPO_ROOT / "golden-config" / "intended-configs"

# Minimum expected config length in characters. Anything shorter than this
# is likely a render failure (empty template output, missing data).
MIN_CONFIG_LENGTH = 200

# Known-benign Batfish parse warnings for IOS-XE
KNOWN_BENIGN_IOS = {
    "ip ssh bulk-mode",
}

# Known-benign Arista EOS parse warnings. These are valid EOS lines that
# Batfish's Arista grammar flags as unsupported or unrecognized (it does not
# fully model multi-agent EVPN or per-vrf BGP neighbors). Kept in sync with
# KNOWN_BENIGN_ARISTA in test_batfish_validate.py.
KNOWN_BENIGN_EOS = {
    "vrf instance",
    "vlan internal order",
    "router bfd",
    "multihop interval",
    "peer group",
    "next-hop-unchanged",
    "address-family evpn",
    "interface Vxlan1",
    "vxlan source-interface",
    "vxlan udp-port",
    "vxlan vlan",
    "vxlan vrf",
    "ip virtual-router mac-address",
    "virtual-router mac-address",
    "ipv6 unicast-routing",
    "maximum-routes",
    "redistribute learned",
    "route-target both",
    "route-target import evpn",
    "route-target export evpn",
    "redistribute connected",
    "_VTEP",
    # EVPN Ethernet Segment (server ESI multihoming). Batfish's Arista grammar
    # does not model the ES identifier or its non-evpn import route-target.
    "identifier 00",
    "route-target import 00",
    # EOS attached-host: redistribute ARP-learned /32s into the SERVERS VRF.
    "ip attached-host route export",
    "attached-host",
}

# Platform detection: files in these directories are EOS
EOS_LOCATIONS = {"dc-a", "dc-b", "dc-c"}
# CE routers are IOS-XE despite being in DC locations
IOS_PREFIXES = {"CE", "SP", "RR", "BORDER"}


def collect_intended_configs() -> list[tuple[str, Path]]:
    """Find all .cfg files under intended-configs/ with their platform hint."""
    configs = []
    if not INTENDED_DIR.exists():
        return configs
    for cfg_file in sorted(INTENDED_DIR.rglob("*.cfg")):
        hostname = cfg_file.stem
        location = cfg_file.parent.name
        # Determine platform from location and hostname prefix
        is_ios = any(hostname.startswith(p) for p in IOS_PREFIXES)
        if is_ios or location == "sp-core":
            platform = "cisco_ios"
        elif location in EOS_LOCATIONS:
            platform = "arista_eos"
        else:
            platform = "cisco_ios"  # default assumption
        configs.append((platform, cfg_file))
    return configs


INTENDED_CONFIGS = collect_intended_configs()


@pytest.mark.skipif(
    not INTENDED_CONFIGS,
    reason="No intended configs found (run Nautobot intended job first)",
)
class TestIntendedConfigSanity:
    """Basic sanity checks on intended config files (no Batfish needed)."""

    @pytest.mark.parametrize(
        "platform,cfg_path",
        INTENDED_CONFIGS,
        ids=[f.stem for _, f in INTENDED_CONFIGS],
    )
    def test_config_not_empty(self, platform, cfg_path):
        """Each intended config must be longer than the minimum threshold."""
        content = cfg_path.read_text()
        assert len(content.strip()) > MIN_CONFIG_LENGTH, (
            f"{cfg_path.name} is only {len(content.strip())} chars. "
            f"Expected >{MIN_CONFIG_LENGTH}. Possible render failure."
        )

    @pytest.mark.parametrize(
        "platform,cfg_path",
        INTENDED_CONFIGS,
        ids=[f.stem for _, f in INTENDED_CONFIGS],
    )
    def test_no_none_in_config(self, platform, cfg_path):
        """Python None should never appear in a rendered config."""
        content = cfg_path.read_text()
        for i, line in enumerate(content.splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith("!") or "description" in stripped.lower():
                continue
            assert " None" not in line and stripped != "None", (
                f"Python 'None' found on line {i} of {cfg_path.name}: {line!r}"
            )

    @pytest.mark.parametrize(
        "platform,cfg_path",
        INTENDED_CONFIGS,
        ids=[f.stem for _, f in INTENDED_CONFIGS],
    )
    def test_no_jinja_artifacts(self, platform, cfg_path):
        """No unrendered Jinja2 syntax in the output."""
        content = cfg_path.read_text()
        assert "{{" not in content, f"Unrendered variable in {cfg_path.name}"
        assert "{%" not in content, f"Unrendered block tag in {cfg_path.name}"

    @pytest.mark.parametrize(
        "platform,cfg_path",
        INTENDED_CONFIGS,
        ids=[f.stem for _, f in INTENDED_CONFIGS],
    )
    def test_starts_with_hostname(self, platform, cfg_path):
        """Config must begin with hostname statement."""
        content = cfg_path.read_text()
        first_line = ""
        for line in content.splitlines():
            if line.strip():
                first_line = line.strip()
                break
        expected = f"hostname {cfg_path.stem}"
        assert first_line == expected, (
            f"Expected '{expected}' as first line, got: {first_line!r}"
        )

    @pytest.mark.parametrize(
        "platform,cfg_path",
        INTENDED_CONFIGS,
        ids=[f.stem for _, f in INTENDED_CONFIGS],
    )
    def test_ends_with_end(self, platform, cfg_path):
        """IOS/EOS configs should end with 'end' statement."""
        content = cfg_path.read_text()
        last_line = ""
        for line in reversed(content.splitlines()):
            if line.strip():
                last_line = line.strip()
                break
        assert last_line == "end", (
            f"{cfg_path.name} doesn't end with 'end'. Last line: {last_line!r}"
        )


# --- Batfish validation of actual intended configs ---

try:
    from pybatfish.client.session import Session

    _bf = Session(host="localhost")
    _bf.set_network("intended-probe")
    BATFISH_AVAILABLE = True
except Exception:
    BATFISH_AVAILABLE = False


def is_benign(text: str, platform: str) -> bool:
    """Check if a parse warning is known-benign for the given platform."""
    stripped = text.strip()
    known = KNOWN_BENIGN_IOS
    if platform == "arista_eos":
        known = known | KNOWN_BENIGN_EOS
    for pattern in known:
        if pattern in stripped:
            return True
    # EOS rd/route-target inside BGP vlan context
    if platform == "arista_eos" and (
        stripped.startswith("rd ") or stripped.startswith("route-target")
    ):
        return True
    return False


@pytest.mark.skipif(
    not BATFISH_AVAILABLE,
    reason="Batfish container not running on localhost:9997",
)
@pytest.mark.skipif(
    not INTENDED_CONFIGS,
    reason="No intended configs found",
)
class TestIntendedConfigsBatfish:
    """Run Batfish parse validation against all actual intended configs."""

    @pytest.fixture(scope="class")
    def batfish_results(self):
        """Load all intended configs into Batfish as a single snapshot."""
        snapshot_dir = "/tmp/batfish_intended_validation"
        if os.path.exists(snapshot_dir):
            shutil.rmtree(snapshot_dir)
        configs_dir = os.path.join(snapshot_dir, "configs")
        os.makedirs(configs_dir)

        # Batfish auto-detects vendor from content, but EOS configs are close
        # enough to IOS that it can fall back to the IOS grammar and emit false
        # warnings on valid EOS syntax (vrf-scoped BGP neighbors, for example).
        # Writing the RANCID header pins the right parser, matching how
        # test_batfish_validate.py builds its snapshot.
        rancid_header = {"arista_eos": "arista", "cisco_ios": "cisco"}
        platform_map = {}
        for platform, cfg_path in INTENDED_CONFIGS:
            hostname = cfg_path.stem
            header = rancid_header.get(platform)
            content = cfg_path.read_text()
            dest = os.path.join(configs_dir, f"{hostname}.cfg")
            with open(dest, "w") as f:
                if header:
                    f.write(f"!RANCID-CONTENT-TYPE: {header}\n")
                f.write(content)
            platform_map[hostname.lower()] = platform

        bf = Session(host="localhost")
        bf.set_network("intended-config-validation")
        bf.init_snapshot(snapshot_dir, name="intended-check", overwrite=True)
        bf.set_snapshot("intended-check")

        parse_status = bf.q.fileParseStatus().answer().frame()
        parse_warnings = bf.q.parseWarning().answer().frame()
        undef_refs = bf.q.undefinedReferences().answer().frame()

        return {
            "parse_status": parse_status,
            "parse_warnings": parse_warnings,
            "undef_refs": undef_refs,
            "platform_map": platform_map,
        }

    def test_no_failed_parses(self, batfish_results):
        """No config file should completely fail to parse."""
        status = batfish_results["parse_status"]
        failed = status[status["Status"] == "FAILED"]
        assert failed.empty, (
            "These configs completely failed to parse:\n"
            + failed["File_Name"].to_string()
        )

    def test_no_unexpected_parse_warnings(self, batfish_results):
        """Only known-benign warnings should appear."""
        warnings = batfish_results["parse_warnings"]
        platform_map = batfish_results["platform_map"]
        unexpected = []

        for _, row in warnings.iterrows():
            # Determine platform from filename
            filename = row["Filename"]
            hostname = Path(filename).stem.lower()
            platform = platform_map.get(hostname, "cisco_ios")

            if not is_benign(row["Text"], platform):
                unexpected.append(
                    f"  {filename}:{row['Line']} - {row['Text'].strip()}"
                )

        assert not unexpected, (
            f"Unexpected parse warnings in intended configs ({len(unexpected)}):\n"
            + "\n".join(unexpected[:20])  # cap at 20 to keep output readable
        )

    def test_no_undefined_references_ios(self, batfish_results):
        """IOS devices should have no undefined route-maps or ACLs."""
        undef = batfish_results["undef_refs"]
        platform_map = batfish_results["platform_map"]

        if undef.empty:
            return

        # Only flag IOS devices (EOS has false positives from mis-detection)
        ios_undef = []
        for _, row in undef.iterrows():
            hostname = Path(row["File_Name"]).stem.lower()
            if platform_map.get(hostname) == "cisco_ios":
                ios_undef.append(
                    f"  {row['File_Name']}: {row['Struct_Type']} '{row['Ref_Name']}'"
                )

        assert not ios_undef, (
            "Undefined references in IOS intended configs:\n"
            + "\n".join(ios_undef)
        )
