query ($device_id: ID!) {
  device(id: $device_id) {
    hostname: name
    config_context
    role {
      name
    }
    tags {
      name
    }
    platform {
      name
      network_driver
      manufacturer {
        name
      }
    }
    location {
      name
      parent {
        name
      }
      vlans {
        vid
        name
        description
        _custom_field_data
        locations {
          name
        }
      }
    }
    interfaces {
      name
      description
      enabled
      type
      mac_address
      mode
      mgmt_only
      role {
        name
      }
      _custom_field_data
      vrf {
        name
        rd
        _custom_field_data
        import_targets {
          name
        }
        export_targets {
          name
        }
      }
      ip_addresses {
        address
        ip_version
        parent {
          prefix
        }
      }
      connected_interface {
        name
        device {
          name
        }
      }
      tags {
        name
      }
    }
    vrfs {
      name
      rd
      _custom_field_data
      import_targets {
        name
      }
      export_targets {
        name
      }
    }
    bgp_routing_instances {
      autonomous_system {
        asn
      }
      router_id {
        address
      }
      extra_attributes
      address_families {
        afi_safi
        vrf {
          name
        }
        extra_attributes
      }
      peer_groups {
        name
        autonomous_system {
          asn
        }
        extra_attributes
        address_families {
          afi_safi
          import_policy
          export_policy
        }
      }
      endpoints {
        enabled
        description
        extra_attributes
        peer_group {
          name
        }
        source_ip {
          address
        }
        source_interface {
          name
        }
        autonomous_system {
          asn
        }
        address_families {
          afi_safi
          import_policy
          export_policy
        }
        peering {
          endpoints {
            source_ip {
              address
            }
            enabled
            autonomous_system {
              asn
            }
            peer_group {
              name
            }
            routing_instance {
              device {
                name
              }
              autonomous_system {
                asn
              }
            }
          }
        }
        peer {
          source_ip {
            address
          }
          autonomous_system {
            asn
          }
          routing_instance {
            device {
              name
            }
            autonomous_system {
              asn
            }
          }
          address_families {
            afi_safi
          }
        }
      }
    }
    igp_routing_instances {
      name
      protocol
      router_id {
        address
      }
      isis_area
      isisconfiguration_set {
        name
        system_id
        default_metric
        interface_configurations {
          interface {
            name
          }
          circuit_type
          network_type
          metric
        }
      }
    }
  }
}
